### ISSUE TITLE
Generating point clouds from synthetic depth maps

### ISSUE THREAD

**Issue by alexbgl** [Healthcare-Robotics/BodyPressure#1]
Hi @henryclever ,

thanks for sharing your great work!

I would like to generate 3D point clouds from the synthetic depth maps, using `x = d * (u - c_x) / f_x`, `y = d * (v - c_y) / f_y` and `z=d`. However, I couldn't figure out how to set the intrinsic camera parameters c_x, c_y, f_x, f_y. Could you guide me on how to appropriately set these parameters? This would be a great help for me.

Thanks

**Comment by henryclever** [comment]
Hi Alex,

This is a very good question. I don't have a straightforward answer (but I wish I did). I am extremely busy at the moment, otherwise I would try to get into the code right now to provide an exact answer.

Here is what I can tell you at the moment: 

The following script converts simulation meshes to depth images via rendering. It it parts VII - IX in fig. 3 in the paper. https://github.com/Healthcare-Robotics/BodyPressure/blob/master/process_data/create_depth_ims_slp.py

So I believe that all of these parameters could be extracted from this script, because you are more or less going "backwards" -- depth --> point cloud rather than scene --> depth.

**Comment by henryclever** [comment]
Hi Alex,

This is a very good question. I don't have a straightforward answer (but I wish I did). I am extremely busy at the moment, otherwise I would try to dig into the code right now to provide an exact answer.

Here is what I can tell you at the moment:

The following script converts simulation meshes to depth images via rendering. It is parts VII - IX in fig. 3 in the paper. https://github.com/Healthcare-Robotics/BodyPressure/blob/master/process_data/create_depth_ims_slp.py

So I believe that all of these parameters could be extracted from this script, because you are more or less going "backwards" -- depth --> point cloud rather than scene --> depth. E.g., line 289 has the field of view for y and the aspect ratio, which you can use to compute both FOV in both directions., and f_x and f_y are a function of fov. But be careful -- the fov on that line is for the kinect. The fov in the depth images in the dataset is smaller, because the depth image is cut off at the edges of the bed.  The code cuts the "original" depth images with rendered FOV to a smaller array. So you should decide if you want the entire point cloud or just the one over the bed. If it's just the one over the bed, c_x and c_y are easy -- height / 2 and width /2 -- 128/2 and 54/2, respectively. But for the original kinect-matched image, c_x and c_y would be bigger than that. You would just have to print out some info in the create_depth_ims_slp.py and figure out what the size was before the cut. 

One worry I have for this is that the images in the dataset may be too low resolution and the point cloud will be quite sparse. If you modify the create_depth_ims_slp.py script you could get an point cloud resolution you wanted by computing the point cloud going forward from the meshes, rather than backward from the 128x54 depth image. 

The meshes that the create_depth_ims_slp.py references are here: 
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DJWQPB 

Let me know if this helps or if you are still stuck!
-Henry

**Comment by alexbgl** [comment]
Hi Henry,

Thank you for your detailed answer, it has already helped me a lot! I would like to ask a few additional questions:

To calculate f_x and f_y from the FOV, I have `f_y = h / (2*tan(FOV_y / 2))` and `f_x = w / (2*tan(FOV_x / 2)) = h / (2*tan(FOV_y / 2)) = f_y`, where h and w are image height and width in px. If I understand your statement "But be careful -- the fov on that line is for the kinect. The fov in the depth images in the dataset is smaller..." correctly, h and w are NOT 128 and 54 but the values from the Kinect, right? In the SLP dataset, this would be h=512 and w=424. However, the resulting aspect ratio 512 / 424 = 1.208 slightly deviates from the aspect ratio specified in line 289, which is 70.6 / 60 = 1.177. So I guess, the size of the synthetic images before cropping is not identical to the size of SLP images and needs to be found by running the script and printing the information, right?

Concerning c_x and c_y, I only need the bed point cloud, so c_x = width / 2 and c_y = height / 2 should generally be fine. However, I am wondering if this is only true if the cropped image is a center crop of the original rendered image. Otherwise, the center of the original image would not coincide with the center of the cropped image, and c_x and c_y would need to be adjusted. Would you agree?

Thanks again,
Alex

**Comment by henryclever** [comment]
Alex, 

I'm sorry for the late response to this -- I didn't forget, just have been busy. You stated: "the size of the synthetic images before cropping is not identical to the size of SLP images." I believe so, but I would really have to go back through the code and run things to check. At the very least, I do not believe that the SLP images and my synthetic images have the same center. I recall the SLP images being eccentric from the center of the bed. In other words, the camera could be in many different translations, so long as it covered the entire bed. Calibration takes care of this, but the original image is still not centered from what I recall.  When I generated synthetic imagery I remember just centering it.

I believe that the synthetic image is centered, originally: Line 378 in `create_depth_ims_slp.py` indicates the depth image is cut from the same amount on both sides: 
depth = depth[53:-53, 72:-73]

I guess it is cut an extra pixel on one side to make the dimension even -- close enough for me.

Overall, getting these images lined up well was a major time sink for me. Very important infrastructure, though.

-Henry

**Comment by alexbgl** [comment]
Thanks again for your detailed answer!
