### ISSUE TITLE
Getting direct output of BoddyPressureWnet

### ISSUE THREAD

**Issue by eitan905** [Healthcare-Robotics/BodyPressure#5]
Hi Henry, I ran 
"python evaluate_depthreal_slp.py --X_is 'W' --slp 'mixedreal' --pmr --mod 2 --v2v --p_idx 83 --ctype 'cover2' --pose_num 25 --savefig"
and managed to run the code and get the nice png's, but I was wondering how I could get the pressure map fit on the model.

I may have misunderstood, so please tell me if I'm wrong. As I understood it the BoddyPressureWnet takes in a Depth image and outputs a Mesh with a Pressure image that fits it, or something similar. in that case how could I get that from the code?

**Comment by henryclever** [comment]
The network inputs a depth image and outputs a mesh and a pressure image. The pressure image can be projected onto the mesh because their relative transform is known.

Did you try this ? 
![bodypressure_pressure_on_mesh](https://user-images.githubusercontent.com/7378478/213525392-9faef3bb-a52a-447c-bf3a-7f901431e5ef.JPG)

**Comment by eitan905** [comment]
I tried but since I run on windows I can't use apt get install to get texlive (or the things you use from it)
And the other windows alternatives like choco and winget don't have texlive

**Comment by henryclever** [comment]
OK - I never tried this repo on Windows (only Ubuntu) so that makes sense. The pressure projection is done in the 3D rendering function, which is at line 268 in the following script: 

https://github.com/Healthcare-Robotics/BodyPressure/blob/5962b31d89483c0449220960b0a27c2044229f19/lib_py/lib_pyrender_depth.py

So my suggestion would be to look through there and inspect the functions that take the network outputs and do the projection on the mesh.

-Henry
