### ISSUE TITLE
how to use my picture

### ISSUE THREAD

**Issue by Saed923** [Healthcare-Robotics/BodyPressure#6]
i want to use model with my picture how can i do this?

**Comment by Saed923** [comment]
thank you

**Comment by henryclever** [comment]
Use the script `evaluate_depthREALTIME.py` . On line 948 you will see that the depth image is initialized to zero. Instead of zero initialize it with your depth image. Make sure you pay attention to the command line options and set them appropriately. If you set the pose_num to something other than 0 it will run it on an existing image rather than yours so you can use that for testing it first.

**Comment by Saed923** [comment]
my picture not good how do i make it like depth_cover1_cleaned_0to102?

**Comment by henryclever** [comment]
Hi, sorry for the late response. I'm not sure about how to make your picture better - there could be a lot of different issues with it. I would suggest trying to identify them and go through and troubleshoot things carefully, and see where you can get.

-Henry
