### ISSUE TITLE
Model Forward 

### ISSUE THREAD

**Issue by Tandon-A** [Healthcare-Robotics/BodyPressure#9]
Hello Henry, 

I have a few doubts related to the forward pass of the data. 

1.  Why is the depth image part set to zero in [unpack_depth_image L139](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/lib_py/unpack_depth_batch_lib_bp.py#L139)?

2. When you are not using v2v loss, then also some comparison is being made on some of the vertices? 
[verts _list](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/train_BPXnet.py#L214)
Later on, in [mesh_depth_lib](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/lib_py/mesh_depth_lib_bp.py#L302) you are using these vertices to obtain posedirs and weights. How are these used?

3. Why are you [reinitializing meshDepthLib](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L95) object for every forward pass? 

4. Later on in [fixedwt_smpl_pmr_net](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L108) you are scaling the CNN output. Any reason for this? Shouldn't the model itself learn this? 

5. What are these constants which are later on added to some variables in [fixedwt_smpl_pmr_net](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L143-L145)?

It's a bit difficult to follow the forward code. Can you help in understanding this?

Best, 
Abhishek

**Comment by henryclever** [comment]
> Hello Henry,
> 
> I have a few doubts related to the forward pass of the data.
> 
> 1. Why is the depth image part set to zero in [unpack_depth_image L139](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/lib_py/unpack_depth_batch_lib_bp.py#L139)?

I believe this code is setting the last row of the depth image (it is 54 x 128) to zero because in the synthetic data I recall there was some issue with the camera position where in some samples it has pixel dropoff (and very high values) in the last row. So it's a bit of a hack to fix that issue with the synthetic data, but you barely lose any information in that single row so it makes little difference. A better way would have been to go through all of the synthetic data and do preprocessing to fix the whole dataset. I think you could probably just delete that line of code and it would hardly make a difference.

> 2. When you are not using v2v loss, then also some comparison is being made on some of the vertices?
>    [verts _list](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/train_BPXnet.py#L214)

Even when I am not using the v2v loss, this will be set to True. So it's effectively "True" in all cases. You could change it to `if True:` rather than `if self.CTRL_PNL['mesh_recon_output'] == True:` and it would make no difference. So I should have updated the code and deleted the one with 10 handpicked vertices. I used these 10 vertices in a much older version of the code when I had some real data with motion capture markers offset from the joints and I wanted to compute a loss from my motion capture markers to their corresponding location on the human mesh. So those 10 vertex indices should correspond to locations close to joints on the SMPL mesh. 


>    Later on, in [mesh_depth_lib](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/lib_py/mesh_depth_lib_bp.py#L302) you are using these vertices to obtain posedirs and weights. How are these used?

Same as above, lines 291 to 396 can be deleted. I just left it there in case I needed it later - it's way faster + efficient to only compute 10 vertices rather than all 6000+ of them. So if you ever want to compute a loss on a sparse set of vertices more efficiently, you can use that code to do it.

> 3. Why are you [reinitializing meshDepthLib](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L95) object for every forward pass?

I'm not - look at L78 - `if CTRL_PNL['first_pass'] == False:`, so every subsequent forward pass it goes there and does not reinitialize.

> 4. Later on in [fixedwt_smpl_pmr_net](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L108) you are scaling the CNN output. Any reason for this? Shouldn't the model itself learn this?

I recall I had some issue with it getting stuck in a bad local minima during the first epoch if I did not do this, and that fixed things. I may have done this in an early iteration of things where something else caused it to get stuck and not things, and just never cleaned up. So maybe it would learn fine without doing that, I'd just have to try and train again and see. 

> 5. What are these constants which are later on added to some variables in [fixedwt_smpl_pmr_net](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L143-L145)?
> 

These are adjustments to the root translation and rotation of the human mesh w.r.t the bed. I defined the world origin translation at the bottom left corner of the bed, so if you don't add these adjustments in the network will start learning with the root joint of the body initialized at the bottom left corner of the bed. But usually the root joint of the body is somewhere close to the middle of the bed, so these adjust it accordingly. This helps it to not get stuck in a local minima when you start training, since the model learns the global pose of the human mesh.


> It's a bit difficult to follow the forward code. Can you help in understanding this?

It's research code! Happy to help answer questions. I learned all of my software skills informally since I'm trained as a Mech E, so my code leaves things to be desired. After that work and almost a year as a SWE in industry I'm sure I'd write better code if I were to do it now. If you are interested in cleaning things up make a merge request and I'm happy to consider merging it in. I just don't have the bandwidth to do it now.
> 
> Best, Abhishek

**Comment by Tandon-A** [comment]
Thanks for the detailed answers. 

I was going through the forward code again and got confused by the part about the [synth_joints_addressed](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L504-L515). Can you explain what is happening here?

**Comment by Tandon-A** [comment]
I guess there is some difference between the synthetic and real datasets. Could you describe [this part](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L572)?

**Comment by henryclever** [comment]
> Thanks for the detailed answers.
> 
> I was going through the forward code again and got confused by the part about the [synth_joints_addressed](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L504-L515). Can you explain what is happening here?

The purpose of this code was to transform a target point at a joint to a close point on the surface of the mesh, for comparison with mocap markers in a previously used dataset. So the knee joint loss would be computed on the surface of the knee rather than in the middle of the joint. But in this paper that should not be happening -- so whatever code is there should have ops that cancel out i.e. it makes no difference. It is possible (but unlikely) that this is a minor bug, and I am actually computing the loss at the surface of the skin on those 10 joints. My next step would be to run the code and print it out and verify what is actually going on, but I'd have to clone the repo+datasets again and see (which I don't have time for at the moment). I did enough visualization that worst case it is a very minor discrepancy and I doubt it affects the results much. 

> I guess there is some difference between the synthetic and real datasets. Could you describe [this part](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/fixedwt_smpl_pmr_net.py#L572)?

This part of the the code needs cleanup. The synth real switch is always `True` for this paper (regardless if I'm using synthetic or real data, so its just confusing code), which means that lines 572 to 576 are functionally the same as lines 580 - 582. You can verify this by inspecting lines 362 - 373 in `networks/train_BPXnet.py`, where `is_synth` is always set to `True`.
